In [2]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.sql.types import *

spark = SparkSession.builder \
        .master('local[*]') \
        .config("spark.driver.memory", "15g") \
        .appName('spark') \
        .getOrCreate()

# Comparison between the 22.06/22.02 V2D data

In [3]:
# Read input files

study_2206 = spark.read.parquet('gs://genetics-portal-dev-staging/v2d/220401/studies.parquet')
study_2202 = spark.read.json('gs://genetics-portal-dev-data/22.02.4/outputs/lut/study-index')

toploci_2206 = spark.read.parquet('gs://genetics-portal-dev-staging/v2d/220401/toploci.parquet')
toploci_2202 = spark.read.parquet('gs://genetics-portal-dev-data/22.02.4/inputs/v2d/toploci_betas_fixed.parquet')

l2g_2206 = spark.read.parquet('gs://genetics-portal-dev-staging/l2g/220613/predictions/l2g.full.220613.parquet')
l2g_2202 = spark.read.parquet('gs://genetics-portal-dev-staging/l2g/220212/predictions/l2g.full.220212.parquet/')

traits_2206 = spark.read.parquet('gs://genetics-portal-dev-staging/v2d/220401/trait_efo.parquet')
traits_2202 = spark.read.parquet('gs://genetics-portal-dev-data/22.02.4/inputs/v2d/trait_efo-2021-02-14.parquet')

## 1. Study table

In [4]:
print('TOTAL Studies 2206:', study_2206.select('study_id').distinct().count())
print('TOTAL Studies 2202:', study_2202.select('study_id').distinct().count())
print('\n')
print('FINNGEN Studies 2206:', study_2206.filter(F.col('study_id').startswith('FINN')).select('study_id').distinct().count())
print('FINNGEN Studies 2202:*', study_2202.filter(F.col('study_id').startswith('FINN')).select('study_id').distinct().count())
print('\n')
print('GWASCAT Studies 2206:', study_2206.filter(F.col('study_id').startswith('GCST')).select('study_id').distinct().count())
print('GWASCAT Studies 2202:', study_2202.filter(F.col('study_id').startswith('GCST')).select('study_id').distinct().count())
print('\n')
print('UKBIOBANK Studies 2206:', study_2206.filter((F.col('study_id').startswith('NEALE')) | (F.col('study_id').startswith('SAIGE'))).select('study_id').distinct().count())
print('UKBIOBANK Studies 2202:', study_2202.filter((F.col('study_id').startswith('NEALE')) | (F.col('study_id').startswith('SAIGE'))).select('study_id').distinct().count())

if not (
    study_2202.filter(F.col('study_id').startswith('FINN')).select('study_id').distinct().count() +
    study_2202.filter(F.col('study_id').startswith('GCST')).select('study_id').distinct().count() +
    study_2202.filter((F.col('study_id').startswith('NEALE')) | (F.col('study_id').startswith('SAIGE'))).select('study_id').distinct().count()
    == study_2202.select('study_id').distinct().count()):
    raise AssertionError ("Check study IDs. There's some mismatch.")

TOTAL Studies 2206: 57246
TOTAL Studies 2202: 50719


FINNGEN Studies 2206: 2861
FINNGEN Studies 2202:* 2924


GWASCAT Studies 2206: 50963
GWASCAT Studies 2202: 44373


UKBIOBANK Studies 2206: 3422
UKBIOBANK Studies 2202: 3422

In [15]:
# Are we missing any study? Yes, 217. Mostly from Finngen - I checked a few cases in the R6 dashboard and they were not there
missed_studies = (
    study_2202.select(F.element_at(F.split('study_id', 'FINNGEN_R5_'), -1).alias('study_id')).distinct()
    .join(study_2206.select(F.element_at(F.split('study_id', 'FINNGEN_R6_'), -1).alias('study_id')).distinct(), on='study_id', how='left_anti')
)

print(missed_studies.count())
print(missed_studies.limit(20).collect())

217
[Row(study_id='ILD_SYST_AUTO_DISEASES'), Row(study_id='INSULIN_SHORTFAST'), Row(study_id='I9_STR_SAH_EXNONE'), Row(study_id='I9_PHLETHROM_EXNONE'), Row(study_id='PULM_MEDICATIO_COMORB'), Row(study_id='DM_DIALYSIS'), Row(study_id='JUVEN_ARTHR_COMORB'), Row(study_id='OPER_JFH'), Row(study_id='TBC_RESP_CLIN'), Row(study_id='GCST012171_3'), Row(study_id='E4_POCS'), Row(study_id='I9_ARTEMBTHRLOW_EXNONE'), Row(study_id='COLITRAD'), Row(study_id='DM_RETINA_PROLIF_NOS_ET_OPER'), Row(study_id='N14_NEPHRITICNAS_ADVERSE'), Row(study_id='I9_REVACS_EXNONE'), Row(study_id='AMPUTATION_TOE'), Row(study_id='I9_ANGIO_EXNONE'), Row(study_id='OPER_SHA03'), Row(study_id='RHEUMA_COMORB')]

#### 1. Why are we losing that many studies in the ETL? 👉 `trait_reported` is null -- Fixed ✅
The problem is mostly happening with UK Biobank studies.

The ETL code that processes the studies: https://github.com/opentargets/genetics-pipe/blob/4fdbbfb06d902f83a77418f9e90aedcb384cc025/src/main/scala/ot/geckopipe/index/V2DIndex.scala#L115

In [31]:
lost_study_example = 'NEALE2_20001_1034'

print('Example of bad study:')
print(pre_etl_study_2206.filter(F.col('study_id') == lost_study_example).show(1, False, True))

print('A good study:')
print(pre_etl_study_2206.filter(F.col('study_id') == 'GCST90025979').show(1, False, True))

Example of bad study:
-RECORD 0---------------------------------
 study_id             | NEALE2_20001_1034
 pmid                 |
 pub_date             | 2018-08-01
 pub_journal          |
 pub_title            |
 pub_author           | UKB Neale v2
 trait_reported       | null
 trait_efos           | null
 ancestry_initial     | [European=361141]
 ancestry_replication | []
 n_initial            | 361141
 n_replication        | 0
 n_cases              | 473
 num_assoc_loci       | 2
 has_sumstats         | true

None
A good study:
-RECORD 0--------------------------------------------------------------------------------------------------------------------------
 study_id             | GCST90025979
 pmid                 | PMID:34226706
 pub_date             | 2021-07-05
 pub_journal          | Nat Genet
 pub_title            | Whole-exome imputation within UK Biobank powers rare coding variant association and fine-mapping analyses.
 pub_author           | Barton AR
 trait_reported       | Alanine aminotransferase levels
 trait_efos           | [EFO_0004735]
 ancestry_initial     | [European=437724]
 ancestry_replication | null
 n_initial            | 437724
 n_replication        | null
 n_cases              | null
 num_assoc_loci       | 339
 has_sumstats         | true

None

#### 2. Are the lost studies in the trait LUT that builds the EFOs? -- Fixed ✅

---> **Yes**. Studies without a reported trait were lost in the process of building the therapeutic area.
One step of this process is to group the LUT on study/reported trait pairs and list all EFOs for that pair.
The grouping function was not null safe and therefore was dropping all the studies where the reported trait was null. This has been fixed.

In [46]:
trait_lut = spark.read.parquet('gs://genetics-portal-dev-staging/v2d/220401/trait_efo.parquet')

trait_lut.filter(F.col('study_id') == lost_study_example).show(1, False, True)

(0 rows)

In [33]:
# This study used to have a mapped term, why is it not there?
study_2202.filter(F.col('study_id') == lost_study_example).show(1, False, True)

-RECORD 0---------------------------------------------------------------------
 ancestry_initial     | [European=361141]
 ancestry_replication | []
 has_sumstats         | true
 n_cases              | 473
 n_initial            | 361141
 n_replication        | 0
 num_assoc_loci       | 2
 pmid                 | null
 pub_author           | UKB Neale v2
 pub_date             | 2018-08-01
 pub_journal          | null
 pub_title            | null
 source               | NEALE
 study_id             | NEALE2_20001_1034
 trait_category       | cell proliferation disorder
 trait_efos           | [EFO_0003865]
 trait_reported       | Kidney/renal cell cancer | cancer code, self-reported

In [6]:
from collections import OrderedDict
import pandas as pd

# Only keep required cols
to_keep = OrderedDict([
    ('code', 'study_id'),
    ('trait', 'trait_raw'),
    ('n_total', 'n_total'),
    ('n_cases', 'n_cases')
])

# Load manifest
manifest = pd.read_csv(tmp, sep="\t", header=0, dtype=object).filter(items=to_keep).rename(columns=to_keep)

manifest.head()

            study_id     trait_raw n_total n_cases
0  NEALE2_100001_raw   Food weight   51453     NaN
1  NEALE2_100002_raw        Energy   51453     NaN
2  NEALE2_100003_raw       Protein   51453     NaN
3  NEALE2_100004_raw           Fat   51453     NaN
4  NEALE2_100005_raw  Carbohydrate   51453     NaN

In [48]:
import re

def make_trait_reported_string(s_raw):
    ''' Takes the raw trait name and outputs trnasformed name
    '''

    # Replace any double spaces with single
    s_raw = re.sub(r' +', r' ', s_raw)

    # Assert no "|" in trait name
    assert "|" not in s_raw

    # Split prefix
    parts = s_raw.split(': ', 1)

    # Move prefix to end if exists
    if len(parts) == 2:
        trait = " | ".join([parts[1], parts[0]])
    else:
        trait = s_raw

    # Capitalise the frist letter
    trait = trait.capitalize()
    
    return trait

manifest['trait_reported'] = (
        manifest['trait_raw'].apply(make_trait_reported_string)
    )

In [47]:
manifest.query("trait_reported != trait_raw").head(20)

,study_id,trait_raw,n_total,n_cases,trait_reported
11,NEALE2_100012_raw,Vitamin B6,51453,NaN,Vitamin b6
12,NEALE2_100013_raw,Vitamin B12,51453,NaN,Vitamin b12
14,NEALE2_100015_raw,Vitamin C,51453,NaN,Vitamin c
19,NEALE2_100021_raw,Vitamin D,51453,NaN,Vitamin d
23,NEALE2_100025_raw,Vitamin E,51453,NaN,Vitamin e
49,NEALE2_100920_0,Type milk consumed: did not have milk,51427,2529.0,Did not have milk | type milk consumed
50,NEALE2_100920_2102,Type milk consumed: semiskimmed,51427,19497.0,Semiskimmed | type milk consumed
51,NEALE2_100920_2103,Type milk consumed: skimmed,51427,10533.0,Skimmed | type milk consumed
52,NEALE2_100920_2104,Type milk consumed: wholemilk,51427,2934.0,Wholemilk | type milk consumed
53,NEALE2_100920_2105,Type milk consumed: soya with calcium,51427,1546.0,Soya with calcium | type milk consumed
54,NEALE2_100920_2106,Type milk consumed: soya without calcium,51427,664.0,Soya without calcium | type milk consumed
55,NEALE2_100920_2107,Type milk consumed: goat/sheep milk,51427,332.0,Goat/sheep milk | type milk consumed
56,NEALE2_100920_2108,Type milk consumed: rice/oat/vegetable milk,51427,299.0,Rice/oat/vegetable milk | type milk consumed
57,NEALE2_100920_2109,Type milk consumed: powdered milk,51427,227.0,Powdered milk | type milk consumed
58,NEALE2_100920_2110,Type milk consumed: cholesterol lowering milk,51427,101.0,Cholesterol lowering milk | type milk consumed
59,NEALE2_100920_2199,Type milk consumed: other type of milk,51427,232.0,Other type of milk | type milk consumed
61,NEALE2_1011,Frequency of light DIY in last 4 weeks,180494,NaN,Frequency of light diy in last 4 weeks
63,NEALE2_1021,Duration of light DIY,179548,NaN,Duration of light diy
108,NEALE2_1070,Time spent watching television (TV),341859,NaN,Time spent watching television (tv)
117,NEALE2_1150_1,Usual side of head for mobile phone use: Left,303009,107802.0,Left | usual side of head for mobile phone use

## 2. Top loci table

In [16]:
toploci_2202 = toploci_2202.withColumn('variant', F.concat(F.col('chrom'), F.lit('_'), F.col('pos'), F.lit('_'), F.col('ref'), F.lit('_'), F.col('alt'))).select('study_id', 'variant', 'pval_mantissa', 'pval_exponent').distinct()
toploci_2206 = toploci_2206.withColumn('variant', F.concat(F.col('chrom'), F.lit('_'), F.col('pos'), F.lit('_'), F.col('ref'), F.lit('_'), F.col('alt'))).select('study_id', 'variant', 'pval_mantissa', 'pval_exponent').distinct()

In [17]:
print('TOTAL Top Loci 2206:', toploci_2206.select('variant').distinct().count())
print('TOTAL Top Loci 2202:', toploci_2202.select('variant').distinct().count())
print('\n')

print('TOTAL Studies in Top Loci 2206:', toploci_2206.select('study_id').distinct().count())
print('TOTAL Studies in Top Loci 2202:', toploci_2202.select('study_id').distinct().count())

TOTAL Top Loci 2206: 156529
TOTAL Top Loci 2202: 142734


TOTAL Studies in Top Loci 2206: 23759
TOTAL Studies in Top Loci 2202: 19885

In [18]:
if (
    # Assert there are no studies in the toploci outside the study table
    toploci_2206.select('study_id').join(study_2206, on='study_id', how='left_anti').distinct().count() > 0
):
    errors = toploci_2206.select('study_id').join(study_2206, on='study_id', how='left_anti').distinct().collect()
    raise AssertionError (f'''
    There are studies in the top loci outside the study table,
    {errors}
    ''')

AssertionError:
    There are studies in the top loci outside the study table,
    [Row(study_id='GCST90095190'), Row(study_id='GCST010653'), Row(study_id='GCST010729')]

In [19]:
# Do the inverse check

if (
    # Assert there is no mismatch between the number of associations between study and top loci table
    study_2202.filter(F.col('num_assoc_loci') > 0).join(toploci_2202, on='study_id', how='left_anti').select('study_id').distinct().count() > 0
):
    errors = study_2202.filter(F.col('num_assoc_loci') > 0).join(toploci_2202, on='study_id', how='left_anti').select('study_id').distinct().collect()
    raise AssertionError (f'''
    There are studies that show association in the study table that are not found in the top loci,
    {errors}
    ''')

In [20]:
# Any lead variants that went missing? Yes, 3827. Should be checked.

print(toploci_2202.join(toploci_2206.select('variant').distinct(), on='variant', how='left_anti').distinct().count())
print(toploci_2202.join(toploci_2206.select('variant').distinct(), on='variant', how='left_anti').distinct().show())

print('\n These seem to be significant associations. The average pValue exponent of the missing loci is ~11.')
print(toploci_2202.join(toploci_2206.select('variant').distinct(), on='variant', how='left_anti').agg({'pval_exponent': 'avg'}).show())

3827
+-------------------+--------------------+------------------+-------------+
|            variant|            study_id|     pval_mantissa|pval_exponent|
+-------------------+--------------------+------------------+-------------+
|    19_13265722_G_A|FINNGEN_R5_CD2_BE...|6.5280000000000005|           -9|
|     12_6013867_T_C|FINNGEN_R5_D3_COA...|             7.259|           -9|
|    1_236268713_C_T|FINNGEN_R5_E4_DM2...| 9.002000000000002|           -9|
|      9_3329838_T_C|   FINNGEN_R5_FG_CVD|             2.705|           -8|
|   11_133199427_G_A|FINNGEN_R5_H7_VIS...|             1.597|           -8|
|    17_64009967_C_T|FINNGEN_R5_I9_THR...|             4.425|           -8|
|    2_142246815_G_C|FINNGEN_R5_I9_VEI...|             9.142|           -9|
|    10_60205819_G_A|FINNGEN_R5_M13_AR...|             4.539|           -8|
|     3_49666644_A_G|          GCST001729|              2.23|          -11|
|    10_36115518_G_A|          GCST007236|4.9590700000000005|          -10|
|    11_88970924_T_C|          GCST007236|           1.69391|           -8|
|    3_114968159_T_A|          GCST007236|           4.42985|           -8|
|    7_141392086_A_G|          GCST007236|3.1080600000000005|           -8|
|    8_115022615_G_C|          GCST007236|            4.4874|          -11|
|16_27226251_G_GTGTA|          GCST007800|               3.4|           -9|
|    2_241740604_T_C|          GCST007800|               6.0|          -18|
|    19_40458157_G_A|        GCST90025973|               6.0|          -16|
|    8_144504778_C_T|        GCST90025979|               1.0|          -62|
|     8_75324016_C_A|FINNGEN_R5_C3_BRE...|             3.123|           -9|
|     8_82391275_C_T|FINNGEN_R5_CD2_BE...|             3.688|           -8|
+-------------------+--------------------+------------------+-------------+
only showing top 20 rows

None

 These seem to be significant associations. The average pValue exponent of the missing loci is ~11.
+-------------------+
| avg(pval_exponent)|
+-------------------+
|-11.084661614841913|
+-------------------+

None

In [21]:
# Any studies in the top loci table went missing? Yes, 1268. 

print(toploci_2202.join(toploci_2206.select('study_id').distinct(), on='study_id', how='left_anti').select('study_id').distinct().count())
print(toploci_2202.join(toploci_2206.select('study_id').distinct(), on='study_id', how='left_anti').select('study_id').distinct().show())

print(study_2206.filter(F.col('study_id').startswith('GCST90016674')).show(2, False, True))

1268
+--------------------+
|            study_id|
+--------------------+
|FINNGEN_R5_CD2_BE...|
|FINNGEN_R5_Q17_CH...|
|FINNGEN_R5_E4_HYT...|
|FINNGEN_R5_I9_HYP...|
|FINNGEN_R5_C3_BRE...|
|FINNGEN_R5_D3_ANA...|
|FINNGEN_R5_KRA_PS...|
|FINNGEN_R5_H7_MOD...|
|FINNGEN_R5_KELA_D...|
|FINNGEN_R5_THYROT...|
|FINNGEN_R5_J10_PE...|
|FINNGEN_R5_O15_CO...|
|FINNGEN_R5_G6_MUS...|
|FINNGEN_R5_M13_MU...|
|FINNGEN_R5_I9_HYP...|
|   FINNGEN_R5_I9_CHD|
|FINNGEN_R5_G6_LSROOT|
|FINNGEN_R5_I9_VAR...|
|FINNGEN_R5_H8_MID...|
|FINNGEN_R5_ST19_P...|
+--------------------+
only showing top 20 rows

None
-RECORD 0-------------------------------------------------------------------------------------------------------
 study_id             | GCST90016674
 ancestry_initial     | [European=32858]
 ancestry_replication | null
 n_cases              | null
 n_initial            | 32858
 n_replication        | null
 pmid                 | PMID:34128465
 pub_author           | Liu Y
 pub_date             | 2021-06-15
 pub_journal          | Elife
 pub_title            | Genetic architecture of 11 organ traits derived from abdominal MRI using deep learning.
 trait_reported       | Liver iron content
 trait_efos           | [EFO_0010056]
 has_sumstats         | true
 num_assoc_loci       | 15
-RECORD 1-------------------------------------------------------------------------------------------------------
 study_id             | GCST90016674_2
 ancestry_initial     | [European=32858]
 ancestry_replication | null
 n_cases              | null
 n_initial            | 32858
 n_replication        | null
 pmid                 | PMID:34128465
 pub_author           | Liu Y
 pub_date             | 2021-06-15
 pub_journal          | Elife
 pub_title            | Genetic architecture of 11 organ traits derived from abdominal MRI using deep learning.
 trait_reported       | Liver iron content [conditional]
 trait_efos           | [EFO_0010056]
 has_sumstats         | false
 num_assoc_loci       | 0

None

## 3. Trait EFOs

In [27]:
print('TOTAL Trait LUT 2206:', traits_2206.count())
print('TOTAL Trait LUT 2202:', traits_2202.count())
print('\n')

print('TOTAL studies in Trait LUT 2206:', traits_2206.select('study_id').distinct().count())
print('TOTAL studies in Trait LUT 2202:', traits_2202.select('study_id').distinct().count())
print('\n')

print('TOTAL EFOs in Trait LUT 2206:', traits_2206.select(F.explode('trait_efos').alias('efo')).distinct().count())
print('TOTAL EFOs in Trait LUT 2202:', traits_2202.select(F.explode('trait_efos').alias('efo')).distinct().count())
print('\n')

print(f'Same schemas: {traits_2206.schema == traits_2202.schema}')

TOTAL Trait LUT 2206: 56317
TOTAL Trait LUT 2202: 49632


TOTAL studies in Trait LUT 2206: 56317
TOTAL studies in Trait LUT 2202: 49632


TOTAL EFOs in Trait LUT 2206: 5260
TOTAL EFOs in Trait LUT 2202: 5041


Same schemas: True